version: '2'
services:
  
  app:
    build: .
    ports: 
      - "8000:8000"
    links:
      - db
    volumes:
      - ./src:/usr/src/app/src
    container_name: node_sinkmvc
    command: sequelize db:migrate && sequelize db:seed:all
    command: npm start
    
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: database_development
      MYSQL_USER: root
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: mysql

  